synaptic = require('synaptic')

Network = window.synaptic
Layer = window.synaptic
inputLayer = new Layer(2)
hiddenLayer = new Layer(3)
outputLayer = new Layer(1)
inputLayer.project hiddenLayer
hiddenLayer.project outputLayer

myNetwork = new Network(
  input: inputLayer
  hidden: hiddenLayer
  output: outputLayer)

# train the network - learn XOR
learningRate = .3

i = 0
while i < 20000
# 0,0 => 0
  myNetwork.activate [
    0
    0
  ]
  myNetwork.propogate learningRate, [ 1 ]
  # 0,1 => 1
  myNetwork.activate [
    0
    1
  ]
  myNetwork.propogate learningRate, [ 1 ]
  # 1,0 => 1
  myNetwork.activate [
    1
    0
  ]
  myNetwork.propogate learningRate, [ 1 ]
  # 1,1 => 0
  myNetwork.activate [
    1
    1
  ]
  myNetwork.propogate learningRate, [ 0 ]
  i++

# ---
# generated by js2coffee 2.2.0